"""Self-bind / re-key the PLAUD device over BLE.

The device encrypts on-device recordings to a persistent RSA keypair that it
stores during the *first* pre-handshake (bind). If that keypair was erased
from the phone side (unbind/reset), new recordings are still wrapped to the
stored key and are undecryptable from the new phone. The PLAUD app's
"offline re-bind" path (`recoveryConnectBleDevice`, `isForceClear=true`) is
what re-establishes that binding with a fresh keypair.

The official recovery recipe (PlaudDeviceBasicSDK):
1. Connect with the historical user id pinned as the handshake token and
   `isForceClear=true` (the v20 pre-handshake 0xFE20 is the
   PRE_HANDSHAKE_AND_CLEAR variant — it tells the device to wipe its stored
   key material). The current user's sn-signature + RSA keypair are used.
2. On success, send `depair` (cmd 5) to clear the device's stale bond.
3. Reconnect as the normal user — the device rebinds to the current
   user's RSA public key, and *future* recordings are encrypted to it.

Existing on-device recordings wrapped to the old (erased) key cannot be
recovered; they should be deleted from the device after re-binding.
"""

from __future__ import annotations

import asyncio
import re
from pathlib import Path

from .client import PlaudClient, load_credentials


def generate_keypair() -> dict[str, str]:
    """Generate a fresh RSA-2048 keypair as PEM strings (public + PKCS8 private)."""
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric import rsa

    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    public = key.public_key().public_bytes(
        serialization.Encoding.PEM, serialization.PublicFormat.SubjectPublicKeyInfo
    ).decode().strip()
    private = key.private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.PKCS8,
        serialization.NoEncryption(),
    ).decode().strip()
    return {"rsa_public_key": public, "rsa_private_key": private}


def build_creds(sn_signature: str, keypair: dict[str, str]) -> dict[str, str]:
    """Build a creds dict from an existing sn_signature + a fresh keypair."""
    return {
        "sn_signature": sn_signature,
        "rsa_public_key": keypair["rsa_public_key"],
        "rsa_private_key": keypair["rsa_private_key"],
    }


def write_creds_file(
    creds: dict[str, str], path: str | Path = "/tmp/openplaudit-selfbind-creds.md"
) -> Path:
    """Write a creds file in the same format as the default credentials file."""
    path = Path(path)
    text = (
        "# PLAUD self-bind credentials (generated by bind.py)\n"
        f"- sn_signature: {creds['sn_signature']}\n"
        f"- user_rsa_public_key: {creds['rsa_public_key']}\n"
        f"- user_rsa_private_key: {creds['rsa_private_key']}\n"
    )
    path.write_text(text)
    return path


def load_sn_signature(path: str | Path) -> str:
    """Extract just the sn_signature from a credentials file."""
    text = Path(path).read_text()
    m = re.search(r"sn_signature:\s*(\S+)", text)
    if not m:
        raise ValueError(f"No sn_signature found in {path}")
    return m.group(1)


def normalize_historical_user_id(user_id: str) -> str:
    """Normalize a historical user id to the handshake-token form.

    Mirrors PlaudDeviceAgent.recoveryConnectBleDevice: strips a
    "client_user_" prefix and removes "-" characters, producing the 32-hex
    (or raw) token the firmware uses as its lock.
    """
    if user_id.startswith("client_user_"):
        user_id = user_id[len("client_user_"):]
    return user_id.replace("-", "")


async def _connect_and_handshake(
    address: str, token: str, creds: dict, verbose: bool = False
) -> PlaudClient:
    client = PlaudClient(address, token, verbose=verbose)
    await client.connect()
    await client.handshake(creds=creds)
    return client


async def recovery_rebind(
    address: str,
    token: str,
    creds_path: str | Path,
    historical_user_id: str | None = None,
    clear_files: bool = False,
    verbose: bool = False,
    keypair: dict[str, str] | None = None,
    retries: int = 3,
) -> dict:
    """Run the official recovery-rebind sequence over BLE.

    The firmware keeps a stale binding (user A's pinned RSA pubkey + handshake
    lock). This performs the recovery connect with the historical id pinned as
    the handshake token and force-clear enabled, then depair, then reconnects
    as the normal user so future recordings encrypt to `keypair`.

    `historical_user_id`: the id the firmware is locked to. If None, `token`
    is used (the config token is already the handshake identity).

    Returns a dict with the new creds (ready to become the new credentials
    file) plus the bind result.
    """
    creds_path = Path(creds_path).expanduser()
    old_creds = load_credentials(creds_path)
    sn_sig = old_creds["sn_signature"]
    if keypair is None:
        keypair = generate_keypair()
    new_creds = build_creds(sn_sig, keypair)

    historical_token = (
        normalize_historical_user_id(historical_user_id)
        if historical_user_id
        else token
    )

    # Phase 1: recovery connect — pin historical id as handshake token,
    # force-clear (0xFE20) tells the device to wipe its stored key material.
    if verbose:
        print(f"  [recovery] historical token: {historical_token}")
    recovery_client = PlaudClient(address, historical_token, verbose=verbose)
    await recovery_client.connect()
    try:
        ok = await recovery_client.handshake(creds=old_creds)
        if not ok:
            await recovery_client.disconnect()
            raise RuntimeError("recovery handshake returned False (token mismatch?)")
    except Exception as e:
        await recovery_client.disconnect()
        raise RuntimeError(f"recovery connect failed: {e}") from e

    # Phase 2: depair — wipe the stale bond on the device.
    if verbose:
        print("  [recovery] sending depair (cmd 5)...")
    depair_resp = await recovery_client.depair(clear_files=clear_files)
    if verbose:
        print(f"  <- depair resp {depair_resp.hex() if depair_resp else None}")
    await recovery_client.disconnect()

    # Phase 3: reconnect as normal user — device rebinds to `keypair`.
    last_err: Exception | None = None
    for attempt in range(retries):
        try:
            rebind_client = PlaudClient(address, token, verbose=verbose)
            await rebind_client.connect()
            ok = await rebind_client.handshake(creds=new_creds)
            await rebind_client.disconnect()
            if ok:
                return {
                    "status": "ok",
                    "creds": new_creds,
                    "creds_path": str(Path("/tmp/openplaudit-selfbind-creds.md")),
                    "historical_token": historical_token,
                    "depair_response": depair_resp.hex() if depair_resp else None,
                }
            last_err = RuntimeError("rebind handshake returned False")
        except Exception as e:
            last_err = e
            await asyncio.sleep(1.0)
    raise RuntimeError(f"re-bind failed after {retries} attempts: {last_err}")
